import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdtemp, rm, readFile } from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';

test('local companion enforces its boundary and preserves room and agent lifecycle', {timeout:45000}, async t=>{
  const root=path.resolve('.');const temp=await mkdtemp(path.join(os.tmpdir(),'fourteenth-test-'));
  const port=44314;const base=`http://127.0.0.1:${port}`;
  const child=spawn(process.execPath,['server/index.mjs','--production'],{cwd:root,env:{...process.env,PORT:String(port),OFFICE_DATA_DIR:temp,OFFICE_CODEX_HOME:path.join(temp,'codex'),OFFICE_CODEX_BIN:process.execPath,OFFICE_CODEX_ARGS:JSON.stringify([path.join(root,'tests/fake-codex.mjs')])},windowsHide:true,stdio:['ignore','pipe','pipe']});
  let stderr='';child.stderr.on('data',d=>stderr+=d);
  t.after(async()=>{ child.kill(); await new Promise(r=>child.once('exit',r)); if(path.resolve(temp).startsWith(path.resolve(os.tmpdir())+path.sep+'fourteenth-test-'))await rm(temp,{recursive:true,force:true}); });
  await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error(stderr||'Server startup timed out')),12000);child.stdout.on('data',d=>{if(String(d).includes('Fourteenth office')){clearTimeout(timer);resolve();}});child.once('exit',()=>reject(new Error(stderr||'Server exited')));});
  assert.equal((await fetch(base+'/api/state')).status,401);
  const page=await fetch(base);const cookie=page.headers.get('set-cookie').split(';')[0];assert.equal(page.status,200);
  const req=async(route,body,method='POST')=>{const r=await fetch(base+'/api'+route,{method:body===undefined?'GET':method,headers:{cookie,...(body===undefined?{}:{'Content-Type':'application/json'})},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:r.status,data:await r.json()};};
  const blocked=await fetch(base+'/api/connect',{method:'POST',headers:{cookie,Origin:'https://untrusted.invalid','Content-Type':'application/json'},body:'{}'});assert.equal(blocked.status,403);
  const initial=await req('/state');assert.equal(initial.data.rooms[0].demo,true);
  const demoBefore=initial.data.rooms[0];
  const rejectedTemplate=await req(`/rooms/${demoBefore.id}/dispatch`,{prompt:'Must not replace the existing mission',templateId:'missing-template'});
  assert.equal(rejectedTemplate.status,409);
  const demoAfter=(await req('/state')).data.rooms.find(room=>room.id===demoBefore.id);
  assert.equal(demoAfter.goal,demoBefore.goal);assert.deepEqual(demoAfter.workItems,demoBefore.workItems);assert.deepEqual(demoAfter.agents,demoBefore.agents);
  const invalid=await req('/rooms',{name:'Bad path',path:'relative/path',demo:true});assert.equal(invalid.status,409);
  const created=await req('/rooms',{name:'Isolated integration test',path:temp,demo:false});assert.equal(created.status,200);const room=created.data.room;
  const connected=await req('/connect',{});assert.equal(connected.data.account.email,'fixture@example.invalid');
  const rejectedModel=await req(`/rooms/${room.id}/dispatch`,{prompt:'Unavailable model must not replace work',model:'missing-model'});
  assert.equal(rejectedModel.status,409);
  const unchangedRoom=(await req('/state')).data.rooms.find(candidate=>candidate.id===room.id);
  assert.equal(unchangedRoom.goal,room.goal);assert.deepEqual(unchangedRoom.workItems,room.workItems);assert.deepEqual(unchangedRoom.agents,room.agents);
  const dispatched=await req(`/rooms/${room.id}/dispatch`,{prompt:'FIXTURE_ARTIFACTS Fixture assignment',model:'fixture-model'});assert.equal(dispatched.status,200);
  await new Promise(r=>setTimeout(r,100));
  let current=(await req('/state')).data.rooms.find(r=>r.id===room.id);let manager=current.agents[0];
  assert.equal(manager.status,'working');assert.equal(manager.progress,50);assert.match(manager.events.find(e=>e.kind==='update').text,/awaiting next action/);assert.doesNotMatch(JSON.stringify(manager),/RAW_PRIVATE_SENTINEL/);
  assert.equal(current.workItems.length,1);assert.equal(current.workItems[0].agentId,manager.id);assert.equal(current.workItems[0].status,'working');assert.equal(current.workItems[0].acceptanceCriteria.length,2);
  const ticket=current.workItems[0],featureRoute=`/rooms/${room.id}/work/${ticket.id}/feature`;
  assert.equal(ticket.evidence.filter(e=>e.source==='observed-turn-diff').length,1);
  assert.equal(ticket.evidence.find(e=>e.source==='observed-turn-diff').text,'+ final change');
  const previewUrl='http://localhost:5173/search?q=keyboard#results';
  const linked=await req(featureRoute,{previewUrl});assert.equal(linked.status,200);assert.equal(linked.data.item.previewUrl,previewUrl);
  assert.equal(linked.data.item.status,ticket.status,'adding a link must not change work status');
  assert.equal((await req(featureRoute,{previewUrl:'javascript:alert(1)'})).status,400);
  assert.equal((await req(featureRoute,{previewUrl:'https://user:secret@example.com/'})).status,400);
  assert.equal((await req('/state')).data.rooms.find(r=>r.id===room.id).workItems[0].previewUrl,previewUrl);
  assert.equal((await req(featureRoute,{previewUrl:''})).data.item.previewUrl,'');
  await req(featureRoute,{previewUrl});
  const originalTurn = manager.turnId;
  assert.equal((await req(`/rooms/${room.id}/agents/${manager.id}/speed`,{fast:'yes'})).status,400);
  const fast = await req(`/rooms/${room.id}/agents/${manager.id}/speed`,{fast:true});
  assert.equal(fast.status,200); assert.equal(fast.data.agent.fastMode,true);
  assert.equal(fast.data.agent.turnId,originalTurn); // Whip never interrupts or starts work.
  assert.equal((await req(`/rooms/${room.id}/agents/${manager.id}/stop`,{})).status,200);
  assert.equal((await req(`/rooms/${room.id}/agents/${manager.id}/message`,{message:'FIXTURE_INTERRUPT_RACE Run with selected speed'})).status,200);
  await new Promise(r=>setTimeout(r,100));
  current=(await req('/state')).data.rooms.find(r=>r.id===room.id); manager=current.agents[0];
  assert.equal(manager.lastRequestedServiceTier,'fast');
  assert.match(manager.events.filter(e=>e.kind==='update').at(-1).text,/Requested tier: fast/);
  assert.equal((await req(`/rooms/${room.id}/agents/${manager.id}/speed`,{fast:false})).status,200);
  assert.equal((await req(`/rooms/${room.id}/agents/${manager.id}/stop`,{})).status,200,'a completed-turn race must not fail pause');
  assert.equal((await req(`/rooms/${room.id}`,{permissionMode:'read-only'},'PATCH')).status,200);
  assert.equal((await req(`/rooms/${room.id}/agents/${manager.id}/message`,{message:'Review with restricted permissions'})).status,200);
  current=(await req('/state')).data.rooms.find(r=>r.id===room.id);manager=current.agents[0];
  assert.equal(manager.threadPermissionKey,'read-only:never');assert.notEqual(manager.threadId,'');
  const readOnlyThread=manager.threadId;
  assert.equal((await req(`/rooms/${room.id}/agents/${manager.id}/stop`,{})).status,200);
  await req(`/rooms/${room.id}`,{permissionMode:'project-write'},'PATCH');
  await req(`/rooms/${room.id}/agents/${manager.id}/message`,{message:'Return to standard'});
  current=(await req('/state')).data.rooms.find(r=>r.id===room.id);manager=current.agents[0];
  assert.equal(manager.threadPermissionKey,'workspace-write:on-request');assert.notEqual(manager.threadId,readOnlyThread);
  assert.ok(manager.previousThreads.includes(readOnlyThread),'permission changes preserve references to prior conversations');

  await new Promise(r=>setTimeout(r,100));
  current=(await req('/state')).data.rooms.find(r=>r.id===room.id); manager=current.agents[0];
  assert.match(manager.events.filter(e=>e.kind==='update').at(-1).text,/Requested tier: default/);
  assert.equal((await req(`/rooms/${room.id}/agents/${manager.id}/message`,{message:'Keep checking'})).status,200);
  assert.equal((await req(`/rooms/${room.id}/agents/${manager.id}/eject`,{})).status,200);
  current=(await req('/state')).data.rooms.find(r=>r.id===room.id);manager=current.agents[0];assert.equal(manager.status,'ejected');assert.match(manager.handoff,/Fixture assignment/);assert.equal(current.workItems[0].previewUrl,previewUrl);assert.equal(current.workItems[0].evidence.find(e=>e.source==='observed-turn-diff').text,'+ final change');assert.equal(manager.turnId,null);
  assert.equal((await req(`/rooms/${room.id}/agents/${manager.id}/speed`,{fast:true})).status,409);
  const replaced=await req(`/rooms/${room.id}/agents/${manager.id}/replace`,{model:'fixture-model'});assert.equal(replaced.status,200);assert.notEqual(replaced.data.agent.id,manager.id);assert.equal(replaced.data.agent.replaces,manager.id);
  assert.equal((await req(`/rooms/${room.id}/agents/${manager.id}/replace`,{model:'fixture-model'})).status,409);
  assert.equal((await req(`/rooms/${room.id}/pause`,{})).status,200);
  current=(await req('/state')).data.rooms.find(r=>r.id===room.id);assert.equal(current.paused,true);assert.equal(current.agents[1].status,'paused');
  assert.equal((await req(`/rooms/${room.id}/install-skills`,{})).status,200);
  assert.match(await readFile(path.join(temp,'.agents/skills/office-manager/SKILL.md'),'utf8'),/sole file writer|sole.*writer|manager is the sole/i);
  assert.equal((await req(`/export/${room.id}`)).data.name,room.name);
  await new Promise(r=>setTimeout(r,650));assert.equal(JSON.parse(await readFile(path.join(temp,'state.json'),'utf8')).rooms.length,2);
});
