import {reviewProject,reviewGuards} from './review-project.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtemp,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
test('real RPC delegation queues dependencies, unblocks verified work, and preserves replay snapshots',{timeout:30000},async t=>{
  const temp=await mkdtemp(path.join(os.tmpdir(),'fourteenth-orchestration-'));const root=path.resolve('.');const base='http://127.0.0.1:44315';
  const project=await reviewProject(temp);
  const child=spawn(process.execPath,['server/index.mjs','--production'],{cwd:root,env:{...process.env,PORT:'44315',OFFICE_DATA_DIR:temp,OFFICE_CODEX_HOME:path.join(temp,'codex'),OFFICE_CODEX_BIN:process.execPath,OFFICE_CODEX_ARGS:JSON.stringify([path.join(root,'tests/fake-codex.mjs')])},windowsHide:true,stdio:['ignore','pipe','pipe']});
  let stderr='';child.stderr.on('data',d=>stderr+=d);
  t.after(async()=>{const exited=new Promise(resolve=>child.once('exit',resolve));child.kill();await exited;if(path.basename(temp).startsWith('fourteenth-orchestration-'))await rm(temp,{recursive:true,force:true});});
  await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error(stderr||'Startup timed out')),10000);child.stdout.on('data',d=>{if(String(d).includes('Fourteenth office')){clearTimeout(timer);resolve();}});});
  const cookie=(await fetch(base)).headers.get('set-cookie').split(';')[0];
  const req=async(route,body)=>{const res=await fetch(base+'/api'+route,{method:body===undefined?'GET':'POST',headers:{cookie,...(body!==undefined?{'Content-Type':'application/json'}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{})});return {status:res.status,data:await res.json()};};
  await req('/connect',{});const {room}= (await req('/rooms',{name:'Queue test',path:project,demo:false})).data;
  assert.equal((await req(`/rooms/${room.id}/dispatch`,{prompt:'FIXTURE_COORDINATE'})).status,200);
  const current=async()=>(await req('/state')).data.rooms.find(r=>r.id===room.id);
  let office;
  for(let i=0;i<40;i++){office=await current();if(office.workItems.length===3)break;await new Promise(r=>setTimeout(r,25));}
  assert.equal(office.workItems.length,3);const [,first,second]=office.workItems;
  assert.equal(first.status,'working');assert.equal(second.status,'queued');assert.match(second.blocker,/dependencies/);assert.equal(office.agents.find(a=>a.id===second.agentId).threadId,undefined);
  assert.equal((await req(`/rooms/${room.id}/agents/${first.agentId}/stop`,{})).status,200);
  assert.equal((await req(`/rooms/${room.id}/work/${first.id}`,{status:'done',evidence:'done'})).status,409);
  assert.equal((await req(`/rooms/${room.id}/work/${first.id}`,{...await reviewGuards(req,`/rooms/${room.id}/work/${first.id}`),status:'done',receipts:[{kind:'log',text:'src/search.ts is the entry point'}],checks:[{index:0,passed:true,evidence:'Inspected src/search.ts'}]})).status,200);
  office=await current();assert.equal(office.workItems[2].status,'working');assert.ok(office.agents.find(a=>a.id===second.agentId).threadId);
  const entry=office.timeline[0];const frame=(await req(`/rooms/${room.id}/timeline/${entry.id}`)).data.frame;assert.ok(frame.agents);assert.equal(office.timeline[0].frame,undefined);
  assert.equal((await req(`/rooms/${room.id}/mode`,{mode:'crunch'})).status,200);assert.equal((await current()).budget,6);
  await req(`/rooms/${room.id}/pause`,{});
  const demo=(await req('/demo',{})).data.room;for(let i=0;i<5;i++)assert.equal((await req(`/rooms/${demo.id}/demo/step`,{})).status,200);
  const parallelDemo=(await req('/demo',{})).data.room;
  await req('/demo',{});
  const demoState=(await req('/state')).data;
  assert.equal(demoState.rooms.find(r=>r.id===demo.id).archived,true,'completed demos may be archived');
  assert.ok(!demoState.rooms.find(r=>r.id===parallelDemo.id).archived,'a second tab must not archive an in-progress demo');
  await req(`/rooms/${demo.id}/archive`,{archived:false});
  const point=(await req(`/rooms/${demo.id}/checkpoints`,{label:'Verified demo'})).data.checkpoint;
  assert.ok(point.id);const branched=await req(`/rooms/${demo.id}/checkpoints/${point.id}/branch`,{});assert.equal(branched.status,200);assert.notEqual(branched.data.room.id,demo.id);assert.equal(branched.data.room.paused,true);
});
