import {reviewProject,reviewGuards} from './review-project.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdtemp, rm, readFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';

test('peer RPC sends directly, queues without restarting, preserves replacement and gates tickets',{timeout:30000},async t=>{
  const temp=await mkdtemp(path.join(os.tmpdir(),'fourteenth-peers-')),root=path.resolve('.'),base='http://127.0.0.1:44321';
  const project=await reviewProject(temp);
  const child=spawn(process.execPath,['server/index.mjs','--production'],{cwd:root,env:{...process.env,PORT:'44321',OFFICE_DATA_DIR:temp,OFFICE_CODEX_HOME:path.join(temp,'codex'),OFFICE_CODEX_BIN:process.execPath,OFFICE_CODEX_ARGS:JSON.stringify([path.join(root,'tests/fake-codex.mjs')])},windowsHide:true,stdio:['ignore','pipe','pipe']});
  let stderr='';child.stderr.on('data',d=>stderr+=d);
  t.after(async()=>{const exited=new Promise(resolve=>child.once('exit',resolve));child.kill();await exited;if(path.dirname(temp)===os.tmpdir() && path.basename(temp).startsWith('fourteenth-peers-'))await rm(temp,{recursive:true,force:true});});
  await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error(stderr||'Startup timed out')),10000);child.stdout.on('data',d=>{if(String(d).includes('Fourteenth office')){clearTimeout(timer);resolve();}});});
  const cookie=(await fetch(base)).headers.get('set-cookie').split(';')[0];
  const req=async(route,body)=>{const res=await fetch(base+'/api'+route,{method:body===undefined?'GET':'POST',headers:{cookie,...(body===undefined?{}:{'Content-Type':'application/json'})},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:res.status,data:await res.json()};};
  await req('/connect',{});const {room}=(await req('/rooms',{name:'Peer test',path:project,demo:false})).data;const endpoint=`/rooms/${room.id}`;
  const current=async()=>(await req('/state')).data.rooms.find(r=>r.id===room.id);
  const wait=async predicate=>{for(let i=0;i<100;i++){const office=await current();if(predicate(office))return office;await new Promise(r=>setTimeout(r,25));}assert.fail('Timed out waiting for peer result');};
  const make=async(title,dependsOn=[])=>{const r=await req(endpoint+'/work',{title,description:'Inspect the search entry point',acceptanceCriteria:['Find concrete evidence'],dependsOn,files:[]});assert.equal(r.status,200);return r.data.item;};
  const first=await make('Research keyboard behavior'),second=await make('Review keyboard behavior');
  assert.equal((await current()).agents.length,1,'creating a ticket never spawns work');
  const a=(await req(endpoint+`/work/${first.id}/assign`,{role:'Research'})).data.agent;
  const b=(await req(endpoint+`/work/${second.id}/assign`,{role:'Review'})).data.agent;
  assert.ok(a.threadId);assert.ok(b.threadId);
  assert.equal((await req(endpoint+`/work/${first.id}/assign`,{role:'Review'})).status,409,'assignment cannot be duplicated');
  const invoke=async(agent,tool,args)=>{
    const before=(await current()).agents.find(x=>x.id===agent.id).events.filter(e=>e.text.startsWith('{"fixtureTool"')).length;
    assert.equal((await req(endpoint+`/agents/${agent.id}/message`,{message:'FIXTURE_TOOL '+JSON.stringify({tool,args})})).status,200);
    const office=await wait(r=>r.agents.find(x=>x.id===agent.id).events.filter(e=>e.text.startsWith('{"fixtureTool"')).length>before);
    return JSON.parse(office.agents.find(x=>x.id===agent.id).events.filter(e=>e.text.startsWith('{"fixtureTool"')).at(-1).text);
  };
  const sent=await invoke(a,'office_message',{agentId:b.id,message:'src/search.ts:18 resets focus; check it.',workItemId:second.id});
  assert.equal(sent.exposed,true);assert.equal(sent.success,true);const id=JSON.parse(sent.contentItems[0].text).messageId;
  let office=await current();assert.equal(office.messages.find(m=>m.id===id).status,'delivered');assert.ok(office.agents.find(x=>x.id===b.id).events.some(e=>e.text.includes('FIXTURE_RECEIVED_INBOX')&&e.text.includes(id)));
  assert.equal((await invoke(a,'office_acknowledge',{messageId:id,note:'Wrong recipient'})).success,false);
  assert.equal((await invoke(b,'office_acknowledge',{messageId:id,note:'Added focus regression to my review.'})).success,true);
  assert.equal((await current()).messages.find(m=>m.id===id).status,'acknowledged');
  assert.equal((await invoke(a,'office_update_work',{workItemId:first.id,status:'done'})).success,false,'specialist cannot change completion gates');
  const failed=await invoke(a,'office_message',{agentId:b.id,message:'FIXTURE_DELIVERY_FAIL'});assert.equal(JSON.parse(failed.contentItems[0].text).status,'queued');
  await req(endpoint+`/agents/${b.id}/stop`,{});
  const queued=await invoke(a,'office_message',{agentId:b.id,message:'Preserve this result for the replacement.'});const queuedId=JSON.parse(queued.contentItems[0].text).messageId;
  office=await current();assert.equal(office.agents.find(x=>x.id===b.id).turnId,null);assert.equal(office.messages.find(m=>m.id===queuedId).status,'queued');
  const replacement=await req(endpoint+`/agents/${b.id}/replace`,{model:'Account default'});assert.equal(replacement.status,200);const successor=replacement.data.agent;
  office=await wait(r=>r.agents.find(x=>x.id===successor.id).events.some(e=>e.text.includes('FIXTURE_RECEIVED_INBOX')));
  assert.equal(office.messages.find(m=>m.id===queuedId).toId,successor.id);assert.equal(office.messages.find(m=>m.id===queuedId).status,'delivered');
  assert.ok(successor.handoffPacket.messages.some(m=>m.id===queuedId));
  await req(endpoint+`/agents/${successor.id}/stop`,{});
  assert.equal((await req(endpoint+`/work/${second.id}`,{status:'done',evidence:'Trust me'})).status,409);
  assert.equal((await req(endpoint+`/work/${second.id}`,{...await reviewGuards(req,endpoint+`/work/${second.id}`),status:'done',receipts:[{kind:'log',text:'Inspected search.ts:18'}],checks:[{index:0,passed:true,evidence:'Reviewed focus path'}]})).status,200);
  const dependent=await make('Dependent review',[first.id]);const dep=(await req(endpoint+`/work/${dependent.id}/assign`,{role:'Review'})).data;
  assert.equal(dep.item.status,'queued');assert.equal(dep.agent.threadId,undefined);
  await new Promise(r=>setTimeout(r,650));const saved=JSON.parse(await readFile(path.join(temp,'state.json'),'utf8'));
  assert.equal(saved.rooms.find(r=>r.id===room.id).messages.find(m=>m.id===id).status,'acknowledged');
});
