import { useEffect, useState } from 'react';
import { ArrowRight, Check, ChevronRight, Circle, Clock3, FileCheck2, GitBranch, Layers, Pause, Play, Plus, RotateCcw, ShieldCheck, Sparkles, X, Zap } from 'lucide-react';
import type { Agent, OfficeState, Room, Tool, WorkItem } from './types';
import './operations.css';
import { WorkArtifacts } from './WorkArtifacts';
export async function officeApi(url:string,body?:unknown) {
  const r=await fetch('/api'+url,{method:body===undefined?'GET':'POST',...(body!==undefined?{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});
  const data=await r.json();if(!r.ok)throw new Error(data.error || 'Request failed');return data;
}
type Action=(fn:()=>Promise<unknown>,success?:string)=>Promise<void>;
export const workLabels={ready:'Ready',queued:'Queued',working:'Working',blocked:'Blocked',review:'Review',done:'Verified'};
export const workColors={ready:'#8a969f',queued:'#8a969f',working:'#477ead',blocked:'#b55c48',review:'#b88732',done:'#38826c'};
export function agentWork(room:Room,a:Agent){return (a.currentWorkItemId?room.workItems.find(t=>t.id===a.currentWorkItemId && !t.archived):room.workItems.find(t=>t.agentId===a.id && !t.archived && t.status!=='done')) || room.workItems.find(t=>t.agentId===a.id && !t.archived);}

export function OfficePulse({room,onTool,onTask,onAdvance,busy}:{room:Room;onTool:(tool:Tool)=>void;onTask:(id:string)=>void;onAdvance:()=>void;busy:boolean}) {
  room={...room,workItems:room.workItems.filter(t=>!t.archived)};
  if(!room.workItems.length)return <section className="office-pulse" aria-label="Office at a glance"><div className="pulse-kicker">{room.name}</div><h1>No tasks yet</h1><div className="button-row"><button className="primary" onClick={()=>onTool('templates')}>Start work <ArrowRight size={14}/></button><button className="secondary" onClick={()=>onTool('dashboard')}>Plan tickets</button></div></section>;
  const done=room.workItems.filter(t=>t.status==='done').length;
  const attention=room.workItems.find(t=>t.status==='blocked') || room.workItems.find(t=>t.status==='review');
  return <section className="office-pulse" aria-label="Office at a glance">
    <div className="pulse-kicker">{room.demo?'DEMO':room.name}{room.paused?' · Paused':''}</div>
    <h1>{room.goal?.split('\n')[0].slice(0,100) || room.workItems.find(t=>t.status==='working')?.title || attention?.title || `${room.workItems.length} tickets`}</h1>
    <div className="pulse-progress"><span>{done}<small> / {room.workItems.length} verified</small></span><button onClick={()=>onTool('dashboard')}>Tickets <ArrowRight size={14}/></button></div>
    <div className="work-segments" aria-hidden="true">{room.workItems.map(t=><i key={t.id} style={{background:workColors[t.status]}} title={t.title}/>)}</div>

    {attention && <button className="attention-link" onClick={()=>onTask(attention.id)}><span className={`signal-dot ${attention.status}`}/><span>{attention.blocker || `Review ${room.agents.find(a=>a.id===attention.agentId)?.name || 'completed work'}`}</span><ChevronRight size={14}/></button>}
    {room.demoStep!=null && <div className="demo-step"><span>{room.demoStep>=5?'DEMO COMPLETE':`SCENE ${room.demoStep+1} / 6`}</span><button className="demo-advance" disabled={busy} onClick={room.demoStep>=5?()=>onTool('replay'):onAdvance}>{room.demoStep>=5?'Replay':'Next step'}<ArrowRight size={13}/></button></div>}
  </section>;
}

function Evidence({item,room,expanded=false,showCriteria=true}:{item:WorkItem;room:Room;expanded?:boolean;showCriteria?:boolean}) {
  return <div className="evidence-dossier">{showCriteria && <><h4>Acceptance criteria</h4>{item.acceptanceCriteria.map((criterion,index)=>{const check=item.checks?.find(c=>c.index===index && c.passed);return <div className={`acceptance-row ${check?'checked':''}`} key={index}>{check?<Check size={15}/>:<Circle size={15}/>}<span>{criterion}{check && !room.demo && <small>{check.evidence}</small>}</span></div>;})}</>}
    <h4>Required evidence</h4><div className="receipt-types">{(item.requiredEvidence || ['log']).map(kind=>{const present=kind==='test' && !room.demo && item.reviewState ? item.reviewState.current : item.evidence.some(e=>e.kind===kind && (kind!=='test'||e.passed));return <span className={present?'present':''} key={kind}>{present?<Check size={12}/>:<Circle size={12}/>} {kind}</span>;})}</div>
    {item.evidence.length===0 && <p className="quiet-copy">No evidence attached.</p>}
    {!!item.evidence.length && <details className="evidence-records"><summary>Evidence · {item.evidence.length}</summary>{item.evidence.map((receipt,i)=><details id={`${item.id}-receipt-${i}`} className="receipt" key={receipt.id || i} data-expanded={expanded || undefined}><summary><FileCheck2 size={14}/>{receipt.kind}<span>{receipt.passed===true?'PASS':receipt.passed===false?'FAIL':'Inspect'}</span></summary>{receipt.source==='cursor-reported' && <p className="quiet-copy">Reported by Cursor · independently verify before accepting.</p>}<pre>{receipt.text}</pre>{receipt.artifact && /\.(png|jpe?g|webp)$/i.test(receipt.artifact) && (room.id.endsWith(':replay')?<p className="quiet-copy">Recorded image path: {receipt.artifact}. Image bytes are not stored in this timeline; the current project file may have changed.</p>:<img alt={`${receipt.kind} artifact`} src={`/api/rooms/${room.id}/artifact?path=${encodeURIComponent(receipt.artifact)}`}/>)} {room.demo && receipt.artifact==='/demo-search.svg' && <><img alt="Simulated project search preview" src="/demo-search.svg"/><a className="text-link" href="/demo/search-preview.html" target="_blank" rel="noreferrer">Try the working search example ↗</a><p className="quiet-copy">Working sample; receipts are simulated.</p></>}</details>)}</details>}
    {!!item.files?.length && <details className="compact-disclosure"><summary>Files · {item.files.length}</summary><div className="file-scope">{item.files.map(file=><code key={file}>{file}</code>)}</div></details>}
  </div>;
}
export function MissionControl({room,data,busy,action,onSelect,onRoom,initialCompose=false,onStarted,onConnect,onTask,onCursor,onCancel}:{onCancel?:()=>void;onCursor:()=>void;onConnect:()=>void;onTask:(id:string)=>void;initialCompose?:boolean;onStarted?:()=>void;room:Room;data:OfficeState;busy:boolean;action:Action;onSelect:(id:string)=>void;onRoom:(id:string)=>void}) {
  const [compose,setCompose]=useState(initialCompose || !room.goal);const [template,setTemplate]=useState('feature');const [prompt,setPrompt]=useState(()=>sessionStorage.getItem(`fourteenth-mission:${room.id}`)||'');
  useEffect(()=>{sessionStorage.setItem(`fourteenth-mission:${room.id}`,prompt);},[prompt,room.id]);
  const cursorOwner=room.agents.find(a=>a.provider==='cursor' && a.turnId);
  const chosen=data.templates.find(t=>t.id===template);
  const [model,setModel]=useState('gpt-6-sol');
  return <div className="operations"><div className="ops-heading"><div>{room.demo && <p className="eyeline">DEMO · NO MODEL EXECUTION</p>}<h2>{compose?'Start work':'Mission board'}</h2></div><button className="template-entry" aria-label={compose?'Cancel new work':'Office templates'} onClick={()=>initialCompose && onCancel?onCancel():setCompose(!compose)}>{compose?<X size={14}/>:<Layers size={14}/>} {compose?'Cancel':'Templates'}</button></div>
    {compose?<form className="mission-composer" onSubmit={e=>{e.preventDefault();action(async()=>{await officeApi(`/rooms/${room.id}/dispatch`,{prompt,model,templateId:template});setCompose(false);setPrompt('');onStarted?.();},'Work started');}}>
      <label>Task<textarea required minLength={3} maxLength={12000} value={prompt} onChange={e=>setPrompt(e.target.value)} rows={3} placeholder="Add instant project search with an accessible empty state."/></label>
      {room.demo && <p className="template-context">Demo · agents do not run.</p>}<label>Workflow<select value={template} onChange={e=>setTemplate(e.target.value)}>{data.templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>
      {chosen && <details className="template-details"><summary>Model and requirements</summary><label>Manager model<select value={model} onChange={e=>setModel(e.target.value)}>{!data.connection.models.some(m=>m.id==='gpt-6-sol') && <option value="gpt-6-sol">GPT-6 Sol</option>}<option>Account default</option>{data.connection.models.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><p className="template-gate"><ShieldCheck size={15}/> Gate: {chosen.required.join(' + ')} + acceptance checks</p><h3>Completion criteria</h3><ul>{chosen.criteria.map(c=><li key={c}>{c}</li>)}</ul></details>}


      {cursorOwner && <p className="notice">Finish or stop the active Cursor assignment before starting a Codex mission.</p>}{!room.demo && !data.connection.account && <><div className="button-row"><button type="button" className="secondary" onClick={onConnect}>Connect Codex</button><button type="button" className="secondary" onClick={onCursor}>Continue in Cursor</button></div><p className="quiet-copy">Your outcome is saved while you connect.</p></>}<button className="primary full" disabled={busy || !!cursorOwner || (!room.demo && !data.connection.account)}><Sparkles size={16}/> {room.demo?'Create demo mission':'Start work'} <ArrowRight size={16}/></button>
    </form>:<><p className="mission-objective">{room.goal}</p><div className="mission-toolbar"><span>{room.workItems.filter(t=>t.status==='done').length}/{room.workItems.length} verified</span>{cursorOwner?<button onClick={()=>onSelect(cursorOwner.id)}>Open Cursor desk <ArrowRight size={13}/></button>:<button disabled={busy} onClick={()=>action(()=>officeApi(`/rooms/${room.id}/${room.paused?'resume':'pause'}`,{}))}>{room.paused?<Play size={13}/>:<Pause size={13}/>} {room.paused?'Resume office':'Pause office'}</button>}</div>
      <div className="task-rail">{room.workItems.filter(t=>!t.archived).map((item,index)=>{const owner=room.agents.find(a=>a.id===item.agentId);return <article className={`rail-task state-${item.status}`} key={item.id}><span className="rail-number" style={{color:workColors[item.status]}}>{item.status==='done'?<Check size={17}/>:String(index+1).padStart(2,'0')}</span><div className="rail-content"><div className="rail-meta"><span style={{color:workColors[item.status]}}>{workLabels[item.status]}</span><span>{owner?.role || 'Unassigned'}</span></div><button className="task-title" onClick={()=>onTask(item.id)}>{item.title}<ChevronRight size={16}/></button>
        <div className="task-owner-row">{owner && <button onClick={()=>onSelect(owner.id)}><i style={{background:owner.color}}/>{owner.name}</button>}<span>{item.evidence.length} receipts</span><span>{item.checks?.filter(c=>c.passed).length || 0}/{item.acceptanceCriteria.length} checks</span></div>
        {item.dependsOn.length>0 && <div className="depends-row"><GitBranch size={12}/>{item.dependsOn.map(id=>{const dependency=room.workItems.find(t=>t.id===id);return <button key={id} onClick={()=>onTask(id)}>{dependency?.status==='done'?'✓ ':''}{dependency?.title || 'Missing dependency'}</button>;})}</div>}
        {item.blocker && <p className="blocked-copy">{item.blocker}</p>}</div></article>;})}</div>
      {room.demoStep!=null && <button className="primary full demo-next" disabled={busy || room.demoStep>=5} onClick={()=>action(()=>officeApi(`/rooms/${room.id}/demo/step`,{}))}><Play size={15}/>{room.demoStep>=5?'Demo complete':'Next step'}<ArrowRight size={15}/></button>}
    </>}
  </div>;
}
export function ModesPanel({room,data,busy,action}:{room:Room;data:OfficeState;busy:boolean;action:Action}) {
  const cursorActive=room.agents.some(a=>a.provider==='cursor' && a.turnId);
  return <div className="operations"><h2>Development mode</h2><p className="quiet-copy">{cursorActive?'Change model and speed in Cursor. These modes control Codex turns.':'Applies to new Codex turns.'}</p><div className="mode-list">{Object.entries(data.modes).map(([id,mode])=><button key={id} aria-pressed={room.mode===id} className={room.mode===id?'selected':''} disabled={busy || cursorActive} onClick={()=>action(()=>officeApi(`/rooms/${room.id}/mode`,{mode:id}),`${mode.name} selected`)}><div><b>{mode.name}</b>{room.mode===id?<Check size={18}/>:<ArrowRight size={15}/>}</div><p>{mode.detail}</p><small><span>{mode.workers} workers</span><span>{mode.effort} effort*</span><span>{mode.minutes} min / turn</span></small></button>)}</div><p className="quiet-copy">* Subject to model support. Crunch/Economy prefer lighter workers; your manager stays selected. Crunch requests fast service and may use more quota.</p></div>;
}
export function ReplayPanel({room,busy,action,onFrame,onRoom,spatial,onSpatial}:{spatial:boolean;onSpatial:()=>void;room:Room;busy:boolean;action:Action;onFrame:(room:Room|null)=>void;onRoom:(id:string)=>void}) {
  const [snapshot,setSnapshot]=useState<Room|null>(null);const [snapshotTask,setSnapshotTask]=useState<string|null>(null);
  const [restoreId,setRestoreId]=useState<string|null>(null);
  const [index,setIndex]=useState(-1);const [playing,setPlaying]=useState(false);const [label,setLabel]=useState('');const [error,setError]=useState('');
  useEffect(()=>{let valid=true;setError('');setSnapshot(null);setSnapshotTask(null);if(index<0){onFrame(null);return;}
    const entry=room.timeline[index];if(!entry)return;
    officeApi(`/rooms/${room.id}/timeline/${entry.id}`).then(result=>{if(valid){const frame={...room,...result.frame,demoGate:result.frame.demoGate,id:`${room.id}:replay`,agents:result.frame.agents.map((a:Agent)=>({...a,talkingUntil:(a.talkingUntil || 0)>result.time?Date.now()+600000:0,ejectedAt:a.status==='ejected'?Date.now():a.ejectedAt}))};setSnapshot(frame);onFrame(frame);}}).catch(e=>{if(valid)setError(e.message);});return()=>{valid=false;};
  },[index,room.id]);
  useEffect(()=>{if(!playing)return;const timer=setInterval(()=>setIndex(i=>{if(i>=room.timeline.length-1){setPlaying(false);return i;}return i+1;}),2400);return()=>clearInterval(timer);},[playing,room.timeline.length]);
  useEffect(()=>()=>onFrame(null),[]);
  return <div className="operations"><div className="history-heading"><h2>History</h2><button className="text-button" onClick={onSpatial}>{spatial?'Hide office':'Show office'}</button></div>{error && <p role="alert" className="blocked-copy">{error}</p>}
    <div className="replay-player"><div><button disabled={!room.timeline.length} aria-label={playing?'Pause replay':'Play replay'} onClick={()=>{if(index>=room.timeline.length-1)setIndex(-1);setPlaying(!playing);}}>{playing?<Pause size={18}/>:<Play size={18}/>}</button><span>{index<0?'Live office':room.timeline[index]?.title}</span><button onClick={()=>{setPlaying(false);setIndex(-1);}}>Live</button></div><input aria-label="Replay position" type="range" min="-1" max={Math.max(-1,room.timeline.length-1)} value={index} onChange={e=>{setPlaying(false);setIndex(Number(e.target.value));}}/></div>
    {snapshot && <section className="snapshot-evidence"><h3>Snapshot evidence</h3><div className="snapshot-tasks">{snapshot.workItems.map(item=><button key={item.id} aria-pressed={snapshotTask===item.id} onClick={()=>{setPlaying(false);setSnapshotTask(item.id);}}>{item.title}<small>{workLabels[item.status]} · {item.evidence.length} receipts</small></button>)}</div>{snapshotTask && <WorkDetail key={`${index}:${snapshotTask}`} room={snapshot} itemId={snapshotTask} onTask={setSnapshotTask} onSelect={()=>{}} readOnly/>}</section>}
    {!room.timeline.length && <p className="quiet-copy">No history yet.</p>}<ol className="replay-list">{room.timeline.map((entry,i)=><li key={entry.id}><button className={i===index?'selected':''} onClick={()=>{setPlaying(false);setIndex(i);}}><span>{String(i+1).padStart(2,'0')}</span><div>{entry.title}<small>{new Date(entry.time).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})} · {entry.kind}</small></div></button></li>)}</ol>

    <div className="checkpoint-header"><Layers size={18}/><h3>Checkpoints</h3></div><p className="quiet-copy">Save with agents stopped. Code checkpoints require a Git repository with a commit. Branch includes tracked code; restore changes office state only.</p>
    {room.agents.some(agent=>agent.provider==='cursor' && !!agent.turnId) ? <p className="notice">Finish or stop in Cursor and release its assignment before saving a checkpoint.</p> : room.agents.some(agent=>!!agent.turnId) && <button className="secondary full" disabled={busy} onClick={()=>action(()=>officeApi(`/rooms/${room.id}/pause`,{}))}><Pause size={14}/> Pause to save a checkpoint</button>}
    <form className="checkpoint-form" onSubmit={e=>{e.preventDefault();action(async()=>{await officeApi(`/rooms/${room.id}/checkpoints`,{label});setLabel('');},'Checkpoint saved');}}><label className="sr-only" htmlFor="checkpoint-label">Checkpoint name</label><input id="checkpoint-label" placeholder="Before the next change" required maxLength={80} value={label} onChange={e=>setLabel(e.target.value)}/><button className="secondary" disabled={busy || index>=0 || room.agents.some(agent=>!!agent.turnId)}><Plus size={16}/> Save</button></form>
    {room.checkpoints.map(point=><div className="checkpoint" key={point.id}><b>{point.label}</b><small>{point.commit?`Code + office · ${point.commit.slice(0,7)}`:'Demo office state'}</small><div><button disabled={busy} onClick={()=>action(async()=>{const result=await officeApi(`/rooms/${room.id}/checkpoints/${point.id}/branch`,{});onRoom(result.room.id);},'Checkpoint branched into a new office')}><GitBranch size={14}/> Branch office</button><button disabled={busy || room.agents.some(a=>!!a.turnId)} onClick={()=>setRestoreId(point.id)}><RotateCcw size={14}/> Restore office only</button></div>{restoreId===point.id && <div className="restore-preview"><p>Restore {room.name} to “{point.label}”? Tickets and agents return to this checkpoint, paused. Files stay unchanged.</p><div className="button-row"><button className="secondary" onClick={()=>setRestoreId(null)}>Cancel</button><button className="primary" disabled={busy} onClick={()=>action(async()=>{await officeApi(`/rooms/${room.id}/checkpoints/${point.id}/restore`,{});setIndex(-1);setRestoreId(null);},'Office restored, paused. Files unchanged.')}>Restore office</button></div></div>}</div>)}
  </div>;
}
export function HandoffDossier({agent}:{agent:Agent}) {
  const packet=agent.handoffPacket;if(!packet)return <p className="quiet-copy">No handoff yet. Stop or replace this agent to preserve its work.</p>;
  return <div className="evidence-dossier"><p className="handoff-saved"><ShieldCheck size={17}/> Context saved {new Date(packet.savedAt).toLocaleTimeString()}</p><details className="compact-disclosure"><summary>Continuation note</summary><p>{packet.instruction}</p></details><h4>Assignment</h4><p>{packet.task}</p><h4>Files</h4><div className="file-scope">{packet.files.map(f=><code key={f}>{f}</code>)}</div><h4>Next steps</h4>{packet.nextSteps.map((s,i)=><p key={i}>{s.step}</p>)}{!packet.nextSteps.length && <p className="quiet-copy">Inspect the assignment and current files before continuing.</p>}<h4>Discoveries</h4>{packet.discoveries.map(e=><pre key={e.id}>{e.text}</pre>)}<h4>Failed attempts</h4>{packet.failedAttempts.length?packet.failedAttempts.map(e=><pre key={e.id}>{e.text}</pre>):<p className="quiet-copy">No failures recorded.</p>}{packet.diff && <details><summary>Preserved diff</summary><pre>{packet.diff}</pre></details>}</div>;
}

export function WorkDetail({room,itemId,onSelect,onTask,readOnly=false,hideHeading=false}:{hideHeading?:boolean;room:Room;itemId:string|null;onSelect:(id:string)=>void;onTask:(id:string)=>void;readOnly?:boolean}) {
  const item=room.workItems.find(task=>task.id===itemId);
  if(!item)return <p className="quiet-copy">Select a task on the map to inspect its acceptance checks, dependencies, and evidence.</p>;
  const owner=room.agents.find(agent=>agent.id===item.agentId);
  const active=!!owner?.turnId || (room.demo && owner?.status==='working');
  return <div className="operations">
    {!hideHeading && <h2>{item.title}</h2>}
    <p className="task-detail-status" style={{color:workColors[item.status]}}><Circle size={11}/>{workLabels[item.status]} · {item.evidence.length} receipts</p>
    {item.evidence.filter(e=>e.kind==='note').at(-1)?.text && <p className="change-summary">{item.evidence.filter(e=>e.kind==='note').at(-1)!.text}</p>}
    <WorkArtifacts key={item.id} room={room} item={item} readOnly={readOnly}/>
    {item.evidence.some(receipt=>receipt.kind==='test') && <div className="receipt-jumps"><button onClick={()=>{const observed=item.evidence.map(receipt=>receipt.kind==='test' && receipt.source==='observed-command').lastIndexOf(true);const index=observed>=0?observed:item.evidence.map(receipt=>receipt.kind).lastIndexOf('test');const receipt=document.getElementById(`${item.id}-receipt-${index}`) as HTMLDetailsElement|null;if(receipt){const group=receipt.closest('.evidence-records') as HTMLDetailsElement|null;if(group)group.open=true;const history=receipt.closest('.review-history') as HTMLDetailsElement|null;if(history)history.open=true;receipt.open=true;receipt.scrollIntoView({block:'start'});}}}>View tests <ArrowRight size={12}/></button></div>}
    {owner && !readOnly && <button className="work-detail-owner" onClick={()=>onSelect(owner.id)}>{owner.name}<small>{owner.effectiveModel || owner.model}</small><ArrowRight size={14}/></button>}
    {item.description!==item.title && <details className="compact-disclosure"><summary>Task description</summary><p>{item.description}</p></details>}{room.demo && <p className="notice">Simulated receipts · no model run.</p>}{room.demoGate?.taskId===item.id && <details className="gate-history" open={item.status!=='done'}><summary>Earlier completion rejected</summary><p>{room.demoGate.gaps.join(' · ')}</p><small>{item.status==='done'?'Required evidence was later attached.':'Evidence required to finish.'}</small></details>}
    {item.blocker && <p className="blocked-copy">{item.blocker}</p>}
    {!!item.dependsOn.length && <div className="depends-row"><GitBranch size={13}/> Depends on {item.dependsOn.map(id=>{const dependency=room.workItems.find(task=>task.id===id);return dependency?<button key={id} onClick={()=>onTask(id)}>{dependency.title}</button>:<span key={id}>Unavailable task</span>;})}</div>}
    <details className="review-history"><summary>Acceptance and evidence</summary><Evidence item={item} room={room} expanded showCriteria={!(hideHeading && !readOnly && owner && !active && item.status!=='done' && !item.archived)}/></details>
  </div>;
}
