export type AgentStatus = 'idle' | 'working' | 'talking' | 'approval' | 'done' | 'paused' | 'error' | 'ejected';
export interface SharedOffice {id:string;name:string;owner:string;paused:boolean;agents:Pick<Agent,'id'|'name'|'role'|'model'|'task'|'status'|'manager'|'color'|'provider'>[];workItems:{id:string;title:string;status:WorkStatus;agentId:string|null;files:string[];blocker:string;receiptCount:number}[]}
export interface TeamConnection {offices?:SharedOffice[];simulated?:boolean;owner:string;connected:boolean;lastSeen:number|null;error:string|null;remote:SharedOffice|null;overlaps:{localTaskId:string;localTitle:string;remoteTaskId:string;remoteTitle:string;files:string[]}[]}
export interface WorkEvent { id: string; kind: string; text: string; time: number; itemId?: string }
export type WorkStatus = 'queued' | 'working' | 'blocked' | 'review' | 'done';
export interface ReviewState { version:string|null; checkedAt:number; current:boolean; passing:number; failing:number; stale:number; label:string; error?:string }
export interface Receipt { id?:string; workspaceVersion?:string|null; stableWorkspace?:boolean; command?:string; source?: string; kind: string; text: string; time: number; passed?: boolean; artifact?: string }
export interface WorkItem { reviewState?:ReviewState; previewUrl?:string; archived?:boolean; priority?:'high'|'normal'|'low'; resumeOnOffice?:boolean; id: string; title: string; description: string; status: WorkStatus; agentId: string | null; dependsOn: string[]; acceptanceCriteria: string[]; requiredEvidence?: string[]; checks?: { index: number; passed: boolean; evidence: string }[]; files?: string[]; evidence: Receipt[]; blocker?: string; createdAt: number; updatedAt: number }
export interface PeerMessage { fromOfficeId?:string;toOfficeId?:string;fromOwner?:string;toOwner?:string;sentByOwner?:boolean;remoteEvidence?:boolean;receivedAt?:number; disposition?:'applied'|'investigate'|'not-applicable'; evidenceLinks?:{workItemId:string;receiptId:string}[]; id:string; from:string; to:string; text:string; time:number; fromId?:string; toId?:string; workItemId?:string; replyTo?:string; kind?:string; status?:'queued'|'delivered'|'acknowledged'; acknowledgement?:string; deliveryError?:string }
export interface OfficeTemplate { id:string; name:string; category:string; description:string; roles:string[]; criteria:string[]; required:string[]; skills:string[] }
export interface OfficeMode { name:string; detail:string; workers:number; minutes:number; effort:string; fast:boolean }
export interface TimelineEntry { id:string; time:number; title:string; kind:string }
export interface Checkpoint { id:string; label:string; time:number; commit:string|null }
export interface Agent { threadPermissionKey?:string; currentWorkItemId?:string; provider?: 'cursor'; effectiveModel?:string; effectiveEffort?:string; deadline?:number; handoffPacket?: {savedAt:number; task:string; files:string[]; discoveries:WorkEvent[]; failedAttempts:WorkEvent[]; nextSteps:{step:string;status:string}[]; diff:string; instruction:string}; fastMode?: boolean; lastRequestedServiceTier?: string; id: string; name: string; role: string; task: string; manager?: boolean; model: string; status: AgentStatus; color: string; progress: number; events: WorkEvent[]; plan: { step: string; status: string }[]; tokens: number; threadId?: string; turnId?: string; talkingUntil?: number; ejectedAt?: number; diff?: string; replaces?: string; replacedBy?: string }
export interface Room { team?:TeamConnection|null; permissionMode?:'project-write'|'read-only'; archived?:boolean; demoGate?:{taskId:string;rejected:boolean;gaps:string[];time:number}; id: string; name: string; path: string; tag: string; demo: boolean; goal: string; mode?:string; templateId?:string; demoStep?:number; timeline:TimelineEntry[]; checkpoints:Checkpoint[]; orchestrationVersion?: number; missionStartedAt?: number | null; workItems: WorkItem[]; agents: Agent[]; messages: PeerMessage[]; skills: string[]; budget: number; paused: boolean }
export interface Approval { id: string; roomId: string; agentId: string; command: string; method: string; questions?: { id: string; header: string; question: string; options?: { label: string; description: string }[] }[] }
export interface OfficeState { templates:OfficeTemplate[]; modes:Record<string,OfficeMode>; version: number; rooms: Room[]; approvals: Approval[]; connection: { testAgents?:boolean; sandboxStatus?: 'ready' | 'notConfigured' | 'updateRequired'; sandboxSetupPending?: boolean; connected: boolean; account: { type: string; email?: string; planType?: string } | null; models: { id: string; name: string; description: string; isDefault: boolean }[]; error?: string | null } }
export type Tool = 'team' | 'dashboard' | 'integrations' | 'office' | 'agents' | 'mission' | 'messages' | 'skills' | 'tools' | 'approvals' | 'settings' | 'connect' | 'rooms' | 'newroom' | 'agent' | 'replay' | 'modes' | 'templates' | 'work' | 'recording';
